spring:
  jpa:
    open-in-view: false
    show-sql: false
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        hibernate.jdbc.time_zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/testekonatus
    username: konatus
    password: konatus
    sql-script-encoding: UTF-8
    initialization-mode: always
  liquibase:
    change-log: classpath:config/liquibase/master.xml
jwt:
  secret: mZwx01MqSYhhs1yowMwBUx6ZH
  issuer: com.konatus